#ifndef LIBFLEX_VERSION_H
#define LIBFLEX_VERSION_H

#define LIBFLEX_VERSION_MAJOR 0
#define LIBFLEX_VERSION_MINOR 1
#define LIBFLEX_VERSION_PATCH 0
#ifdef LIBFLEX_GIT_HASH
#define LIBFLEX_VERSION_STRING "0.1.0+" LIBFLEX_GIT_HASH
#else
#define LIBFLEX_VERSION_STRING "0.1.0"
#endif

#endif
