#ifndef LIBFLEX_VERSION_H
#define LIBFLEX_VERSION_H

#define LIBFLEX_VERSION_MAJOR 1
#define LIBFLEX_VERSION_MINOR 0
#define LIBFLEX_VERSION_PATCH 2
#ifdef LIBFLEX_GIT_HASH
#define LIBFLEX_VERSION_STRING "1.0.2+" LIBFLEX_GIT_HASH
#else
#define LIBFLEX_VERSION_STRING "1.0.2"
#endif

#endif
